name: Github CI
on: [push]

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." 
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!" 
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - uses: actions/checkout@v5

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-name: scrna
          channels: conda-forge,bioconda
          channel-priority: strict
          activate-environment: scrna

      - name: Install dependencies
        env:
          MPLBACKEND: Agg
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        run: |
          conda install -y -c conda-forge -c bioconda \
            alevin-fry \
            salmon \
            pyroe \
            python-igraph \
            scanpy

          python -m pip install -U pip

          pip install -r requirements.txt
          pip install leidenalg
          pip install mygene
          pip install celltypist
          pip install jupyter nbclient

      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Week 6
        run: |
          conda run -n scrna jupyter nbconvert --to notebook --execute week6/week6.ipynb
