name: Github CI
on: [push]

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." 
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!" 
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - uses: actions/checkout@v5

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-name: scrna
          channels: conda-forge,bioconda
          channel-priority: strict
          activate-environment: scrna

      - name: Install dependencies
        run: |
          conda install -y -c conda-forge -c bioconda \
            alevin-fry \
            salmon \
            pyroe \
            python-igraph \
            scanpy

          pip install leidenalg
          pip install mygene
          pip install celltypist

      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Download toy_read_ref_set.tar.gz
        run: |
          SHARE_URL="https://app.box.com/s/lx2xownlrhz3us8496tyu9c4dgade814"
          HTML=$(curl -L -s "$SHARE_URL")
          DIRECT_URL=$(echo "$HTML" | grep -o 'https://public.boxcloud.com/api/2.0/files/[0-9]\+/content[^"]*' | head -n 1)
          echo "Direct download URL: $DIRECT_URL"
          curl -L "$DIRECT_URL" -o week6/toy_read_ref_set.tar.gz
          
      - name: Week 6
        run: |
          conda run -n scrna jupyter nbconvert --to notebook --execute week6/week6.ipynb
